title: Stocktify
description: "August 2023 to June 2024"
owner_name: Theo Huntalas
github_username: TheoH32
github_repo: "Stocktify"
baseurl: "/Stocktify"
remote_theme: jekyll/minima
repository: TheoH32/Stocktify
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/TheoH32"}
    - { platform: github, user_url: "https://github.com/kaiden-dough"}
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
