title: Stocktify
description: "Stocktify"
owner_name: Theo Huntalas
github_username: TheoH32
github_repo: "Stocktify"
baseurl: "/Stocktify"
remote_theme: jekyll/minima
repository: TheoH32/Stocktify
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
